code-message: "Rollem's code may be found at https://github.com/lemtzas/Rollem"
help-message: "Help may be found on the wiki at https://github.com/lemtzas/Rollem/wiki"
owner-message: "The Owner of this bot is Lemtzas (https://twitter.com/lemtzas) (lemtzas@gmail.com)"
issues-message: "Bugs or feature reequests may be placed here: (https://github.com/lemtzas/Rollem/issues)"
